### Get all users
GET http://localhost:8080/api/users HTTP/1.1

### Get one user
GET http://localhost:8080/api/users/<userId> HTTP/1.1

### Create a user
POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "first_name": "Eugenie",
  "last_name": "Jeary",
  "email": "ejeary1@themeforest.net",
  "gender": "Female",
  "age": 59
}

### Patch user.
PUT http://localhost:8080/api/users/<userId>
Content-Type: application/json

{
  "first_name": "Ivan Zaldivar"
}

### Patch user.
PATCH http://localhost:8080/api/users/<userId>
Content-Type: application/json

{
  "first_name": "Ivan Zaldivar"
}

### Remove a user
DELETE  http://localhost:8080/api/users/<userId> HTTP/1.1
